baseURL = "https://example.com"
languageCode = "en-us"
title = "Bowie"
theme="bowie"
copyright = "Â© Stepan Zwicknagl"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
  mode="auto"
  useCDN=false
  subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/stephanzwicknagl/bowie)"
  mainSectonsTitle = "Latest Posts and Contributions"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/stephanzwicknagl/bowie"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
